import LoginPage from "@/pages/LoginPage/LoginPage";

export const metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
      <LoginPage />
    </div>
  );
}
