import SignUpPage from "@/pages/registerpage";

export const metadata = {
  title: "Register",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
      <SignUpPage />
    </div>
  );
}
